jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      - task: PowerShell@2
        displayName: "Install dependencies"
        inputs:
          targetType: 'inline'
          script: |
            cd tests
            npm ci

      - task: AzureCLI@2
        displayName: Run Playwright Test (Azure Grid)
        env:
          PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
          PLAYWRIGHT_SERVICE_RUN_ID: $(Build.DefinitionName)-$(Build.BuildNumber)-$(System.JobAttempt)
        inputs:
          azureSubscription: 'PlaywrightTestSpace'
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            cd tests
            npx playwright test --config=playwright.service.config.js
          addSpnToEnvironment: true

      - task: PublishPipelineArtifact@1
        displayName: Upload Playwright report
        inputs:
          targetPath: tests/playwright-report/
          artifact: 'Playwright-tests'
          publishLocation: 'pipeline'