jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      - script: npm ci
        displayName: "Install dependencies"
        workingDirectory: tests/

      - script: npx playwright install --with-deps
        displayName: "Install Playwright Browsers"
        workingDirectory: tests/

      - task: AzureCLI@2
        displayName: Run Playwright Test
        env:
          PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
          PLAYWRIGHT_SERVICE_RUN_ID: $(Build.DefinitionName) - $(Build.BuildNumber) - $(System.JobAttempt)
        inputs:
          azureSubscription: 'PlaywrightTestSpace'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            npx playwright test --config=playwright.service.config.js
          addSpnToEnvironment: true
        workingDirectory: tests/

      - task: PublishPipelineArtifact@1
        displayName: Upload Playwright report
        inputs:
          targetPath: tests/playwright-report/
          artifact: 'Playwright-tests'
          publishLocation: 'pipeline'