trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Playwright_Tests
  displayName: Run Playwright Tests on Azure Grid

  steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: '18.x'

  - script: |
      node -v
      npm -v
    displayName: Verify Node Installation

  - script: |
      cd tests
      npm ci
    displayName: Install Dependencies

  - task: AzureCLI@2
    displayName: Run Playwright Tests (Azure Grid)
    env:
      PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
      PLAYWRIGHT_SERVICE_RUN_ID: $(Build.DefinitionName)-$(Build.BuildNumber)-$(System.JobAttempt)
    inputs:
      azureSubscription: 'PlaywrightTestSpace'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        node -v
        npx playwright test Calender.spec.js --config=../playwright.service.config.js
      addSpnToEnvironment: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Playwright Report
    inputs:
      targetPath: tests/playwright-report/
      artifact: Playwright-Report
      publishLocation: pipeline